# travis 
language: ruby
rvm:
  - 2.1.2
cache:
  directories:
    - vendor/bundle
before_script:
  - "cp ./config/database.yml.travis ./config/database.yml"
  - mysql -e 'create database portfolio_website_test;'
  - "bundle exec rake db:nuke_pave"
env:
  global:
    - CI=true
gemfile:
  - Gemfile
